# Generated by Django 2.2.2 on 2019-06-20 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Low'), (1, 'Normal'), (2, 'High')], default=1),
        ),
    ]
