# Generated by Django 2.2.2 on 2019-06-24 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kto', '0006_auto_20190624_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
